catalogMode: prefer
cleanupUnusedCatalogs: true

ignoreWorkspaceRootCheck: true

shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - 'packages/*'

catalogs:
  build:
    obuild: ^0.4.31
  cli:
    c12: ^3.3.3
    cac: ^7.0.0
    convert-gitmoji: ^0.1.5
    escalade: ^3.2.0
    jsonc-parser: ^3.3.1
    package-manager-detector: ^1.6.0
    semver: ^7.7.4
    zx: ^8.8.5
  dev:
    '@antfu/eslint-config': ^7.6.1
    arkregex: ^0.0.5
    cspell: ^9.7.0
    eslint: ^10.0.2
    eslint-plugin-format: ^2.0.1
    markdownlint-cli2: ^0.21.0
    ts-json-schema-generator: ^2.9.0
    vitest: ^4.0.18
  logging:
    loglevel: ^1.9.2
  types:
    '@types/fs-extra': ^11.0.4
    '@types/node': ^25.3.3
    '@types/semver': ^7.7.1
    typescript: ^5.9.3

includeWorkspaceRoot: true

onlyBuiltDependencies:
  - esbuild
