catalogMode: prefer
cleanupUnusedCatalogs: true

ignoreWorkspaceRootCheck: true

shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - 'packages/*'

catalogs:
  build:
    obuild: ^0.4.7
  cli:
    c12: ^3.3.2
    cac: ^6.7.14
    convert-gitmoji: ^0.1.5
    escalade: ^3.2.0
    jsonc-parser: ^3.3.1
    package-manager-detector: ^1.6.0
    semver: ^7.7.3
    zx: ^8.8.5
  dev:
    '@antfu/eslint-config': ^6.6.1
    arkregex: ^0.0.4
    cspell: ^9.4.0
    eslint: ^9.39.1
    eslint-plugin-format: ^1.1.0
    eslint-plugin-import: ^2.32.0
    gh-pages: ^6.3.0
    markdownlint-cli2: ^0.20.0
    ts-json-schema-generator: ^2.4.0
    vitest: ^4.0.15
  logging:
    loglevel: ^1.9.2
  types:
    '@types/fs-extra': ^11.0.4
    '@types/node': ^24.10.2
    '@types/semver': ^7.7.1
    typescript: ^5.9.3

includeWorkspaceRoot: true

onlyBuiltDependencies:
  - esbuild
