name: Setup Node and pnpm
description: Setup Node.js, pnpm, pnpm cache, and install dependencies

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: '22'
  registry-url:
    description: Optional npm registry URL
    required: false
    default: ''
  install:
    description: Run pnpm install after setup
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        cache: true

    - name: Setup Node.js
      if: ${{ inputs.registry-url == '' }}
      uses: actions/setup-node@v6
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}

    - name: Setup Node.js with registry
      if: ${{ inputs.registry-url != '' }}
      uses: actions/setup-node@v6
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - name: Install dependencies
      if: ${{ inputs.install == 'true' }}
      shell: bash
      run: pnpm install
