name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: Lint, Build, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          node-version: '22'
          pnpm-version: ''

      - name: Build packages
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test
